### ISSUE TITLE
Please Release Code

### ISSUE THREAD

**Issue by cdefg** [MCZhi/GameFormer#3]
Hello MCZhi,
  I appreciate your work and had similar ideas as yours, so I got very interesed in your work. I can't wait to see what you actually do in this code. I would be very appreciative if you could release the code soon.

**Comment by MCZhi** [comment]
@cdefg Thank you for your interest in our work. We want to inform you that we are currently preparing for the code release. Our plan is to make it available shortly after ICCV's Announcement of decisions, which is scheduled for July 13.

**Comment by cdefg** [comment]
See your works, thank you for sharing!
