### ISSUE TITLE
Data processing of training_20s

### ISSUE THREAD

**Issue by wangyy0** [MCZhi/GameFormer#4]
I am very interested in your work and have similar thoughts. When running your code, in the data processing stage, there is a problem with training_20s, it cannot process the results.

for int_id in objects_of_interest:
       interact_list.append(id_list[int_id])

An error will be reported in this command, and id_list is empty.

**Comment by MCZhi** [comment]
@georgeliu233, can you help look into this issue?

**Comment by georgeliu233** [comment]
> I am very interested in your work and have similar thoughts. When running your code, in the data processing stage, there is a problem with training_20s, it cannot process the results.
> 
> for int_id in objects_of_interest: interact_list.append(id_list[int_id])
> 
> An error will be reported in this command, and id_list is empty.

Hi, sorry for the late response！

If you are referring to the Waymo interactive prediction task, the training set is processed upon ```training``` , which are pre-sliced in 1+8s window for easier training, instead of using ```training_20s```. The error is likely to be caused by missing annotations of ```tracks_to_predict``` in training_20s

**Comment by CHAIJZ888** [comment]
I've encountered a problem at the moment: the installation of waymo-open-dataset-tf-2-11-0 is not successful. I'm getting the following error message:ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-11-0 (from versions: none)
ERROR: No matching distribution found for waymo-open-dataset-tf-2-11-0
I'm curious to know if this project is only compatible with Linux systems. I appreciate your response!Best regards.

**Comment by MCZhi** [comment]
@CHAIJZ888, please see #5.
