### ISSUE TITLE
ERROR: waymo-open-dataset-tf-2-11-0

### ISSUE THREAD

**Issue by CHAIJZ888** [MCZhi/GameFormer#5]
Hello! I came across your paper and found it to be excellent – truly impressive and intriguing. If I can build on your work to achieve results, I will certainly cite your paper. However, I've encountered a problem at the moment: the installation of waymo-open-dataset-tf-2-11-0 is not successful. I'm getting the following error message:ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-11-0 (from versions: none)
ERROR: No matching distribution found for waymo-open-dataset-tf-2-11-0
I'm curious to know if this project is only compatible with Linux systems. I appreciate your response!Best regards.

**Comment by MCZhi** [comment]
We only tested it on Linux systems. So we would highly recommend conducting your experiments on a Linux platform.
