### ISSUE TITLE
Encoding object_type in Class AgentEncoder

### ISSUE THREAD

**Issue by WahabF** [MCZhi/GameFormer#7]
There may be a problem with encoding the object type in the Class AgentEncoder. 
You are using

`type = self.type_emb(inputs[:, -1, 8].int())` 

And since object_type is one hot vector, I think the vector should be transformed into an integer first as: 

`object_type = (inputs[:, -1, 8:].argmax(dim=-1)+1)* inputs[:, -1, 8:].sum(dim=-1).int()
  type = self.type_emb(object_type)`

**Comment by MCZhi** [comment]
I think there is a clash in data processing about agents between open-loop planning and interaction prediction. Can you help me look into this issue, @georgeliu233?

**Comment by georgeliu233** [comment]
Yep thats a slight difference in data_process and I will fix this to align the model structure.

**Comment by MCZhi** [comment]
I have fixed this issue in data_process for interaction prediction.
