### ISSUE TITLE
does refline use the future information of ego

### ISSUE THREAD

**Issue by wzhi05** [MCZhi/GameFormer#8]
It seems that the calculation of refline use the future information of ego traj. In this function  “find_route”:
```
def find_route(traj, timestep, cur_pos, map_lanes, map_signals):
    lane_polylines = get_polylines(map_lanes)
    end_lane, end_point = find_map_waypoint(np.array((traj[-1].center_x, traj[-1].center_y, traj[-1].heading)), lane_polylines)
    cur_lane, _ = find_map_waypoint(cur_pos, lane_polylines)
    
    path_waypoints = []
    for t in range(0, len(traj), 10):
        lane, point = find_map_waypoint(np.array((traj[t].center_x, traj[t].center_y, traj[t].heading)), lane_polylines)
        path_waypoints.append(lane_polylines[lane][point])

    after_waypoints = []
    for waypoint in lane_polylines[end_lane][end_point:]:
        after_waypoints.append(waypoint)
    if len(after_waypoints) < 100:
        if map_lanes[end_lane].exit_lanes:
            lane = map_lanes[end_lane].exit_lanes[0]
            for waypoint in lane_polylines[lane]:
                after_waypoints.append(waypoint)

    waypoints = np.concatenate([path_waypoints, after_waypoints[::5]], axis=0)

    # generate smooth route
    tx, ty, tyaw, tc, _ = generate_target_course(waypoints[:, 0], waypoints[:, 1])
    ref_line = np.column_stack([tx, ty, tyaw, tc])
    
    # get reference path at current timestep
    current_location = np.argmin(np.linalg.norm(ref_line[:, :2] - cur_pos[np.newaxis, :2], axis=-1))
    start_index = np.max([current_location, 0])
    ref_line = ref_line[start_index:start_index+1000]

    # add speed limit and traffic signal info to ref route
    line_info = np.zeros(shape=(ref_line.shape[0], 1))
    speed_limit = map_lanes[cur_lane].speed_limit_mph / 2.237
    ref_line = np.concatenate([ref_line, line_info], axis=-1)
    signals = [Point([signal.stop_point.x, signal.stop_point.y]) for signal in map_signals[timestep].lane_states if signal.state in [1, 4, 7]]

    for i in range(ref_line.shape[0]):
        if any([Point(ref_line[i, :2]).distance(signal) < 0.2 for signal in signals]):
            ref_line[i, 4] = 0 # red light
        else:
            ref_line[i, 4] = speed_limit

    return ref_line
    
```

For the calculation of variable "path_waypoints",  it seem that the future traj of ego is included.

**Comment by MCZhi** [comment]
Yes, the refinement step requires the future ego trajectory to find the reference path. This is because WOMD does not provide this information for planning purposes. However, in the nuPlan dataset, which can be found at [GameFormer-Planner](https://github.com/MCZhi/GameFormer-Planner), the route information is provided, so we do not require the future ego trajectory.

**Comment by wzhi05** [comment]
Get it.  Another question is how long did you take to parse the Waymo motion 1.1 dataset?  For validation dataset（30+G） in Waymo motion 1.1 , it seems to take about a week to parse the raw data. 
I just use this commend to parse data.  I'm thinking if there's a problem with my configuration.
```
python data_process.py \
--load_path path/to/your/dataset/training_20s \
--save_path path/to/your/processed_data \
--use_multiprocessing \
```

**Comment by MCZhi** [comment]
How many files are in your validation dataset? If you are using multiprocessing normally, it shouldn't take too long. However, if you are experiencing issues, try removing the `--use_multiprocessing` parameter and see if it helps.

**Comment by wzhi05** [comment]
> How many files are in your validation dataset? If you are using multiprocessing normally, it shouldn't take too long. However, if you are experiencing issues, try removing the `--use_multiprocessing` parameter and see if it helps.

I use all the data files(150 files) in the validation dataset from Waymo open dataset motion 1.1. and the size of validation is 36G.

**Comment by MCZhi** [comment]
Then it shouldn't take too long. Have you tried parsing the raw data without using multiprocessing?

**Comment by wzhi05** [comment]
> Then it shouldn't take too long. Have you tried parsing the raw data without using multiprocessing?

Yes, I used  multiprocessing for data parsing. My computer has 32 CPU cores, is this the reason for long time parsing.

**Comment by MCZhi** [comment]
I don't know the exact reason, but I recommend trying to run the code without multiprocessing to get an idea of how long it takes. This will help you determine if using multiprocessing is actually speeding up the data processing. Usually, multiprocessing can significantly accelerate the process, but it might encounter some problems that could slow it down.

**Comment by wzhi05** [comment]
> encounter some problems that could slow i

Thank you,  I will try this way to see the effect.
